name: CI Workflow with Variables
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print repository name
        run: echo "Repository name is ${{ github.repository }}"

      - name: Print custom message
        run: |
          echo "Custom message: ${MY_MESSAGE}"
        env:
          MY_MESSAGE: ${{ vars.MY_MESSAGE != '' && vars.MY_MESSAGE || 'Hello DevOps!' }}